version: '3.8'
services:
  api:
    image: 951516963/dotzfidelidadeapi:latest   
    ports:
      - "1986:80"
    networks:
      - minha_rede
    depends_on:
      - mysql_db
    environment: 
      ConnectionStrings__MySql: "server=mysql_db;database=dotzfidelidade;user=banana;password=banana"

  mysql_db:
    image: mysql:8.0
    networks:
      - minha_rede
    environment: 
      MYSQL_DATABASE: dotzfidelidade
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banana
      MYSQL_PASSWORD: banana

networks: 
  minha_rede: 
    driver: bridge 